### ISSUE TITLE
Confirm soilpsi functioning correctly

### ISSUE THREAD

**Issue by bpbond** [PNNL-TES/millenial#1]
```R
> soilpsi(sand = 40, silt = 40, clay = 20, vwc = .4, vwcsat = .8, organic = 10)
psi:  -0.1760069 -0.002530615 -6.12 -1 210.3183 5.829231 0.07692308 10 2.7 
$psisat
[1] -0.002530615

$psi
[1] -0.1760069

$smp_l
[1] -1
```
Do we get the same results from the Fortran version?

**Comment by bpbond** [comment]
I started by translating the shortest and simplest routine, `soilpsi`. 

@email-clm Would it be possible for you to run the Fortran version with the test parameters shown above and paste the output here? That will let us check that the R version produces identical output.

I don't have a Fortran compiler installed currently, but could do it if it's a hassle for you–just let me know. Thanks!

**Comment by bpbond** [comment]
Also @rabramoff and @email-clm does this help page for `soilpsi` look correct?

<img width="507" alt="screen shot 2019-03-06 at 9 28 44 am" src="https://user-images.githubusercontent.com/1956468/53888334-39733d80-3ff2-11e9-865e-1aa49d3fd377.png">

**Comment by rabramoff** [comment]
Using your inputs, I get exactly what you get (see below message; apologies for raw output copy/paste). BUT I'm not sure the units that you report in the previous comment are right. I think though the code mentions that sand/silt/clay is in percent, it might actually be fraction (0-1), and we should also double check the organic matter units with Xiaofeng. Otherwise everything looks good.
   
40.0000000     =sand
40.0000000     =silt
20.0000000     =clay
0.400000006     =vwc
0.800000012     =vwcsat
10.0000000     =organic
 -0.176006854      -2.53061485E-03  -6.11999989      -1.00000000       210.318283       5.82923079       7.69230798E-02   10.0000000       2.70000005     =psi, psisat, bsw2, smp_l, sucsat, bsw, om_frac, organic, om_b
-0.176006854     =psi
-2.53061485E-03 =psisat
-1.00000000     =smp_l

**Comment by bpbond** [comment]
@rabramoff great! 👍  And thanks, I wondered about the fraction versus percentage thing. Will change the documentation.

**Comment by bpbond** [comment]
>we should also double check the organic matter units with Xiaofeng

I closed this via commit, but @email-clm the code says OM is kg/m3; correct? Thanks.

**Comment by email-clm** [comment]
Hi Ben and Rose,

Yes, you guys got the functions correctly. Yes, the unit for OM is kg/m3.

Xiaofeng
