### ISSUE TITLE
Questions about soilpsi code

### ISSUE THREAD

**Issue by bpbond** [PNNL-TES/millenial#5]
Hi @rabramoff @email-clm 

See below for a few questions about `soilpsi`, at your convenience, as I'd like to add some explanatory comments to the code if possible. I've prefixed with line numbers for easy reference.

```fortran
 849 	om_sucsat = 10.3_r8    	! saturated suction for organic matter (Lets, 2000)
 850 	smpmin = -1._r8    	! restriction for min of soil potential line 750 of iniTimeConst.F90
```
1. What does `iniTimeConst.F90` refer to?

```fortran
 851 	organic_max = 130._r8
 852 	om_b = 2.7_r8
 ```
2. What's `om_b`? Where does this value come from?

```fortran
 858 	om_frac = min(organic / organic_max, 1._r8)
 859 	sucsat = 10. * ( 10.**(1.88-0.0131*sand) )
 860 	bsw = (1.-om_frac)*(2.91 + 0.159*clay) + om_frac*om_b   
```
3. What's `bsw` and is there a reference for these two equations?

```fortran
 861 	sucsat = (1.-om_frac)*sucsat + om_sucsat*om_frac  
 862 	s_node = min(1.0, max(vwc / vwcsat, 0.01))	    
 863 	smp = max(smpmin, (-sucsat * (s_node ** (-bsw))))
 864 	smp_l = smp
 865 	bsw2 = -(3.1 + 0.157 * clay - 0.003 * sand)
 866 	psisat = -(exp((1.54 - 0.0095*sand + 0.0063*(100.0-sand-clay))*log(10.0))*9.8e-5_r8)
```
4. If `sand`, `silt`, and `clay` are fractions (see #1 ) why are they being subtracted from 100 here? 
5. Is there a citation for this equation?

Thanks!

**Comment by email-clm** [comment]
Let me check, will get back to you shortly.

Xiaofeng

**Comment by email-clm** [comment]
Sorry the unit for sand, silt, clay is percentage (0-100%).
The original functions for soil water potential are from CLM. Since the CLM
needs to refer to many other functions, the Millennial model has similar
but not exactly same variable names.

that is why you see some codes refer to iniTimeConst.F90 in CLM. Many
variables have been assigned a value, rather than directly read
iniTimeConst.F90 file (since we do not have that file in this model).

om_b is a Clapp Hornberger paramater for oragnic soil (Letts, 2000)
bsw is Clapp and Hornberger "b"

the calculation for soil hydraulic properties are from below reference, I
briefly read them in 2012 when I was in ORNL.
https://agupubs.onlinelibrary.wiley.com/doi/10.1029/WR014i004p00601

If you are able to access CLM code, you can find detailed there, the
variable names are not exactly same.

Otherwise, you can access those codes at
https://github.com/email-clm/clm-microbe/blob/6cb5c2c989e19797ad8f6c5b095eb5f45900850d/models/lnd/clm/src/clm4_5/main/iniTimeConst.F90.
this repo holds the model code revised in my lab. My lab added a microbial
module (bacteria/fungi/DOM) and microbial functional group-based CH4 module
into CLM. But did not change any code for the soil hydraulic. Hydrology was
changed little as well.

Best,
Xiaofeng

**Comment by bpbond** [comment]
That's fantastic–thank you.
